version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 
    commands:
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - npm run heroku-postbuild
      - npm prune --production
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - '**/*'
cache:
  paths:
    - node_modules
