//User reducer constants
const SET_NAME = "SET_NAME"
const SET_AGE = "SET_AGE"
const REGISTER_SUCCESS = "REGISTER_SUCCESS";
const REGISTER_FAIL = "REGISTER_FAIL";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";
const LOGOUT = "LOGOUT";

//Product reducer constants
const SET_PRODUCT = "SET_PRODUCT";
const APPEND_PRODUCT = "APPEND_PRODUCT";
const EDIT_PRODUCT = "EDIT_PRODUCT;"
const APPENDING = "APPENDING";
const APPENDED = "APPENDED";

//Order reducer constants
const SET_ORDER = "SET_ORDER";
const APPEND_ORDER = "APPEND_ORDER";
const EDIT_ORDER = "EDIT_ORDER";
const UPDATE_STATUS = "UPDATE_STATUS";
const DELETE_ORDER ="DELETE_ORDER";

//Checkout history tracker
const SET_CHECKOUT_IN_HISTORY = "SET_CHECKOUT_IN_HISTORY";
const CLEAR_CHECKOUT_FROM_HISTORY = "CLEAR_CHECKOUT_FROM_HISTORY";

//loader constants
const SET_LOADER = "SET_LOADER"
const SET_PAGINATION = "SET_PAGINATION"
const SET_PAGE_STATE = "SET_PAGE_STATE"
export {
     SET_NAME,
     SET_AGE,
     REGISTER_SUCCESS,
     REGISTER_FAIL,
     LOGIN_SUCCESS,
     LOGIN_FAIL,
     LOGOUT,
     SET_CHECKOUT_IN_HISTORY,
     CLEAR_CHECKOUT_FROM_HISTORY,
     SET_PRODUCT,
     APPEND_PRODUCT,
     EDIT_PRODUCT,
     UPDATE_STATUS,
     DELETE_ORDER,
     APPENDING,
     APPENDED,
     SET_ORDER,
     EDIT_ORDER,
     APPEND_ORDER,
     SET_LOADER,
     SET_PAGINATION,
     SET_PAGE_STATE
     }