module.exports = {
  ACCOUNT_NOT_FOUND: "account not found",
  INCORRECT_PASSWORD: "email or password is incorrect",
  ACCOUNT_DEACTIVATED: "oops, your account has been deactivated, contact admin",
  NO_PRIVILEGE:
    "you do not have the required privilege to perform this operation",
  UNKNOWN: "an unexpected error has occured",
  EXPIRED_TOKEN: "Expired token",
  UNAUTHORIZED: "Unauthorized",
  UNAUTHORIZED_TOKEN: "Unauthorized token",
  EXPIRED_OR_INVALID_TOKEN: "Expired or invalid token",
  REQUIRED_EMAIL_PASSWORD: "Email, password and name are required",
  INVALID_EMAIL: "Invalid email",
  INVALID_PASSWORD: "Invalid pasword",
  INVALID_NAME: "Invalid name",
  INVALID_PHONE: "Invalid phone number",
  EMAIL_IN_USE: (email) => `an account with email ${email} already exists`,
  NO_TOKEN_FOUND: "Please provide a token",
  DUPLICATE_USER_REVIEW: "Duplicate user review",
  USER_HAS_NO_REVIEW: "User has no review",
  PRODUCT_NOT_FOUND: "Product not found",
  DUPLICATE_PRODUCT_IN_ORDER: "Duplicate product in a single order",
  NOT_FOUND:
    "Could not find what you are looking for please check our documentation for more details",
};
